version: "3.9"

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      CONNECTION_STRING: postgresql+psycopg2://postgres:test@db:5432/vector_db
      OPENAI_API_KEY: ${OPEN_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - .:/app

volumes:
  pgdata:
